### ISSUE TITLE
Multiple datacenters

### ISSUE THREAD

**Issue by thefosk** [thibaultCha/lua-cassandra#48]
Supporting a LB policy so that the driver can properly handle multi-datacenter setups.

**Comment by thefosk** [comment]
Does #45 close this issue? @thibaultCha

**Comment by thibaultCha** [comment]
It implements [dc_rr.lua](https://github.com/thibaultCha/lua-cassandra/blob/master/lib/resty/cassandra/policies/lb/dc_rr.lua) for now, which is the simplest form of LB policy but it prioritizes those in the local cluster.
There is still some manual work to do, because when initializing the cluster module in a given OpenResty instance, it needs to be given the name of the local datacenter, as in:

```lua
local dc_rr = require 'resty.cassandra.policies.lb.dc_rr'
local Cluster = require 'resty.cassandra.cluster'

local cluster = assert(Cluster.new {
  contact_points = {...},
  lb_policy = dc_rr.new('my_local_datacenter_name')
})
```

**Comment by thibaultCha** [comment]
Supported by 1.0.0.
