### ISSUE TITLE
attempt to call method 'settimeout' (a nil value) 

### ISSUE THREAD

**Issue by architm21** [thibaultcha/lua-cassandra#76]
attempt to call method 'settimeout' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua: in function 'check_peer_health'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:340: in function 'first_coordinator'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:408: in function 'refresh'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:682: in function 'execute'
any idea about this ??

**Comment by thibaultcha** [comment]
`client:settimeout()` is defined in this library's `cassandra` module, exactly [here](https://github.com/thibaultcha/lua-cassandra/blob/master/lib/cassandra/init.lua#L276).

Could it be that you are using another module under the `cassandra` namespace that is conflicting with this one? Namely, jbochi/lua-resty-cassandra? If so, I would suggest removing it so that this library's `cassandra` module can be properly loaded.

**Comment by architm21** [comment]
well removing jbochi/lua-resty-cassandra solved the issue.   
thanks for your help 👍
